
volumes:
  mongo-data:

networks:
  net-geral:

services:
 
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - net-geral
    restart: always

  mongo-express:
    image: mongo-express
    container_name: express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_AUTH_USERNAME  : root
      ME_CONFIG_MONGODB_AUTH_PASSWORD  : example
    restart: always
    ports:
      - 8081:8081
    networks:
      - net-geral
    depends_on:
      - mongo

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "5001:5001"
    networks:
      - net-geral
    environment:
      - NODE_ENV=production
      - PORT=5001

      - DB_USER=root
      - DB_PASS=example
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=tests
      - DEV=false
    restart: always
    depends_on:
        - mongo

  front:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile-next
    ports:
      - 3000:3000
    networks:
      - net-geral
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://ip172-18-0-16-cvf8khq91nsg00bs1rb0-5001.direct.labs.play-with-docker.com

    restart: always

    depends_on:
        - api

