# Stage 1: Build the application
FROM node:18-alpine AS builder

# Define working directory
WORKDIR /app

# Install Git (necessário para clonar o repositório)
RUN apk add --no-cache git

# Clone the repository
RUN git clone https://github.com/AlexsandroJ/frontESS.git .

# Install dependencies
RUN npm install

# Build the Next.js application
RUN npm run build

# Stage 2: Serve the application
FROM node:18-alpine AS runner

# Define working directory
WORKDIR /app

# Copy only the necessary files from the builder stage
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# Expose the port that Next.js runs on
EXPOSE 3000

# Start the application
CMD ["npm", "run dev"]