# Use uma imagem Node.js oficial
FROM node:18-alpine

# Define o diretório de trabalho
WORKDIR /app

# Instala o Git para clonar o repositório
RUN apk add --no-cache git

# Clone o repositório da API
RUN git clone https://github.com/AlexsandroJ/apiESS.git .

# Instala as dependências
RUN npm install

# Expõe a porta que a API usa (por exemplo, 5000)
EXPOSE 5001

# Inicia a API
CMD ["npm", "start"]